// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: protos/risk.proto

package riskpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TradeRiskRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AssetId   string  `protobuf:"bytes,1,opt,name=assetId,proto3" json:"assetId,omitempty"`
	Volume    float64 `protobuf:"fixed64,2,opt,name=volume,proto3" json:"volume,omitempty"`
	Action    string  `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Timestamp string  `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *TradeRiskRequest) Reset() {
	*x = TradeRiskRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_risk_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TradeRiskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeRiskRequest) ProtoMessage() {}

func (x *TradeRiskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_risk_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeRiskRequest.ProtoReflect.Descriptor instead.
func (*TradeRiskRequest) Descriptor() ([]byte, []int) {
	return file_protos_risk_proto_rawDescGZIP(), []int{0}
}

func (x *TradeRiskRequest) GetAssetId() string {
	if x != nil {
		return x.AssetId
	}
	return ""
}

func (x *TradeRiskRequest) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *TradeRiskRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *TradeRiskRequest) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type TradeRiskResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Allowed bool   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Reason  string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	CheckId string `protobuf:"bytes,3,opt,name=checkId,proto3" json:"checkId,omitempty"`
}

func (x *TradeRiskResponse) Reset() {
	*x = TradeRiskResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_risk_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TradeRiskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeRiskResponse) ProtoMessage() {}

func (x *TradeRiskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_risk_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeRiskResponse.ProtoReflect.Descriptor instead.
func (*TradeRiskResponse) Descriptor() ([]byte, []int) {
	return file_protos_risk_proto_rawDescGZIP(), []int{1}
}

func (x *TradeRiskResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *TradeRiskResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *TradeRiskResponse) GetCheckId() string {
	if x != nil {
		return x.CheckId
	}
	return ""
}

var File_protos_risk_proto protoreflect.FileDescriptor

var file_protos_risk_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x72, 0x69, 0x73, 0x6b, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x72, 0x69, 0x73, 0x6b, 0x22, 0x7a, 0x0a, 0x10, 0x54, 0x72, 0x61,
	0x64, 0x65, 0x52, 0x69, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x73, 0x73, 0x65, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x73, 0x73, 0x65, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73,
	0x74, 0x61, 0x6d, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x5f, 0x0a, 0x11, 0x54, 0x72, 0x61, 0x64, 0x65, 0x52, 0x69,
	0x73, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x6c,
	0x6c, 0x6f, 0x77, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x61, 0x6c, 0x6c,
	0x6f, 0x77, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07,
	0x63, 0x68, 0x65, 0x63, 0x6b, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63,
	0x68, 0x65, 0x63, 0x6b, 0x49, 0x64, 0x32, 0x50, 0x0a, 0x0b, 0x52, 0x69, 0x73, 0x6b, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x65, 0x72, 0x12, 0x41, 0x0a, 0x0e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x54, 0x72,
	0x61, 0x64, 0x65, 0x52, 0x69, 0x73, 0x6b, 0x12, 0x16, 0x2e, 0x72, 0x69, 0x73, 0x6b, 0x2e, 0x54,
	0x72, 0x61, 0x64, 0x65, 0x52, 0x69, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x17, 0x2e, 0x72, 0x69, 0x73, 0x6b, 0x2e, 0x54, 0x72, 0x61, 0x64, 0x65, 0x52, 0x69, 0x73, 0x6b,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x72, 0x69,
	0x73, 0x6b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_risk_proto_rawDescOnce sync.Once
	file_protos_risk_proto_rawDescData = file_protos_risk_proto_rawDesc
)

func file_protos_risk_proto_rawDescGZIP() []byte {
	file_protos_risk_proto_rawDescOnce.Do(func() {
		file_protos_risk_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_risk_proto_rawDescData)
	})
	return file_protos_risk_proto_rawDescData
}

var file_protos_risk_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protos_risk_proto_goTypes = []interface{}{
	(*TradeRiskRequest)(nil),  // 0: risk.TradeRiskRequest
	(*TradeRiskResponse)(nil), // 1: risk.TradeRiskResponse
}
var file_protos_risk_proto_depIdxs = []int32{
	0, // 0: risk.RiskChecker.CheckTradeRisk:input_type -> risk.TradeRiskRequest
	1, // 1: risk.RiskChecker.CheckTradeRisk:output_type -> risk.TradeRiskResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_risk_proto_init() }
func file_protos_risk_proto_init() {
	if File_protos_risk_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_risk_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TradeRiskRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_risk_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TradeRiskResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_risk_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_risk_proto_goTypes,
		DependencyIndexes: file_protos_risk_proto_depIdxs,
		MessageInfos:      file_protos_risk_proto_msgTypes,
	}.Build()
	File_protos_risk_proto = out.File
	file_protos_risk_proto_rawDesc = nil
	file_protos_risk_proto_goTypes = nil
	file_protos_risk_proto_depIdxs = nil
}
