// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: protos/risk.proto

package riskpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	RiskChecker_CheckTradeRisk_FullMethodName = "/risk.RiskChecker/CheckTradeRisk"
)

// RiskCheckerClient is the client API for RiskChecker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RiskCheckerClient interface {
	CheckTradeRisk(ctx context.Context, in *TradeRiskRequest, opts ...grpc.CallOption) (*TradeRiskResponse, error)
}

type riskCheckerClient struct {
	cc grpc.ClientConnInterface
}

func NewRiskCheckerClient(cc grpc.ClientConnInterface) RiskCheckerClient {
	return &riskCheckerClient{cc}
}

func (c *riskCheckerClient) CheckTradeRisk(ctx context.Context, in *TradeRiskRequest, opts ...grpc.CallOption) (*TradeRiskResponse, error) {
	out := new(TradeRiskResponse)
	err := c.cc.Invoke(ctx, RiskChecker_CheckTradeRisk_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RiskCheckerServer is the server API for RiskChecker service.
// All implementations must embed UnimplementedRiskCheckerServer
// for forward compatibility
type RiskCheckerServer interface {
	CheckTradeRisk(context.Context, *TradeRiskRequest) (*TradeRiskResponse, error)
	mustEmbedUnimplementedRiskCheckerServer()
}

// UnimplementedRiskCheckerServer must be embedded to have forward compatible implementations.
type UnimplementedRiskCheckerServer struct {
}

func (UnimplementedRiskCheckerServer) CheckTradeRisk(context.Context, *TradeRiskRequest) (*TradeRiskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckTradeRisk not implemented")
}
func (UnimplementedRiskCheckerServer) mustEmbedUnimplementedRiskCheckerServer() {}

// UnsafeRiskCheckerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RiskCheckerServer will
// result in compilation errors.
type UnsafeRiskCheckerServer interface {
	mustEmbedUnimplementedRiskCheckerServer()
}

func RegisterRiskCheckerServer(s grpc.ServiceRegistrar, srv RiskCheckerServer) {
	s.RegisterService(&RiskChecker_ServiceDesc, srv)
}

func _RiskChecker_CheckTradeRisk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TradeRiskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskCheckerServer).CheckTradeRisk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskChecker_CheckTradeRisk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskCheckerServer).CheckTradeRisk(ctx, req.(*TradeRiskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RiskChecker_ServiceDesc is the grpc.ServiceDesc for RiskChecker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RiskChecker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "risk.RiskChecker",
	HandlerType: (*RiskCheckerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckTradeRisk",
			Handler:    _RiskChecker_CheckTradeRisk_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/risk.proto",
}
